services:
  postgres:
    image: postgres:16
    container_name: postgres_cuentas
    environment:
      POSTGRES_DB: cuentas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./base-cuentas.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cuentas-network

  api:
    build: .
    container_name: cuentas_api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cuentas_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - cuentas-network

networks:
  cuentas-network:
    driver: bridge

volumes:
  postgres_data: